# Name: Deploy Message

# Manual trigger

# Inputs:
# app-name → string
# environment → choice: dev, test, prod

# Step 1:
# id: deploy-info
# Create output:
# message=Deploying APP_NAME to ENVIRONMENT

# Step 2:
# Print the message output
name: Deploy Message

on:
  workflow_dispatch:
    inputs:
      app-name:
        type: string
        required: true

      environment:
        type: choice
        required: true
        options:
          - dev
          - test
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: deploy step
        id: deploy-info
        run: echo "message=Deploying ${{ inputs.app-name }} to ${{ inputs.environment }}" >> "$GITHUB_OUTPUT"

      - name: print step
        run: echo "${{ steps.deploy-info.outputs.message }}"
       
