name: testing number input
on:
  workflow_dispatch: 
    inputs:
      Environment:
        required: true
        description: "enter a number"
        type: number
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: printing name
        run: echo "hi ${{ inputs.Environment }}"

  
