name: testing string input
on:
  workflow_dispatch: 
    inputs:
      Environment:
        required: true
        description: "enter your name"
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: printing name
        run: echo "hi ${{ inputs.Environment }}"

  
