name: testing  input
on:
  workflow_dispatch: 
    inputs:
      Environment:
        required: true
        description: "enter do you think True or false"
        type: boolean
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: printing name
        run: echo "hi ${{ inputs.Environment }}"

  
