name: CI


on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  noor:
    runs-on: ubuntu-latest

    steps:
      - name: printing something
      
        run: echo "hello noor" 


    

    

 
