name: practice1
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: printing manual worflow
        run: |
          echo "Starting Maven workflow"
          echo "Level 1 completed"
  
