# Modify the workflow so it:

# Checks out your repository code.
# Displays all files and folders in the repository.
# # Keeps the existing printing step.

name: practice2
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checksout repo
        uses: : actions/checkout@v4
      - name: printing req output
        run: |
          ls
          echo "Starting Maven workflow"
          echo "Level 1 completed"
        
  
