name: test1
on: 
  workflow_dispatch:
    inputs:
      message:
        description: Enter the text
        
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: printing value
        run: echo "hello message"
        
          
        
        
