name: workflow practice
on: 
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checking out repo
        uses: actions/checkout@v4
      - name: setting java version
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - name: printing files and messages
        run: |
          mvn clean compile
          ls
           echo "Starting Maven workflow"
           echo "Level 3 completed"
